//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: XNFMsgBase.proto
// Note: requires additional types generated from: NFDefine.proto
// Note: requires additional types generated from: XNFDefine.proto
namespace XNFMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroInfo")]
  public partial class HeroInfo : global::ProtoBuf.IExtensible
  {
    public HeroInfo() {}
    
    private int _hero_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private byte[] _player_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] player_name
    {
      get { return _player_name; }
      set { _player_name = value; }
    }
    private readonly global::System.Collections.Generic.List<XNFMsg.HeroInfo> _hero_list = new global::System.Collections.Generic.List<XNFMsg.HeroInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"hero_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<XNFMsg.HeroInfo> hero_list
    {
      get { return _hero_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}