//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: NFMsgMysql.proto
namespace NFMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackMysqlParam")]
  public partial class PackMysqlParam : global::ProtoBuf.IExtensible
  {
    public PackMysqlParam() {}
    
    private byte[] _strRecordName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"strRecordName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] strRecordName
    {
      get { return _strRecordName; }
      set { _strRecordName = value; }
    }
    private byte[] _strKey;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"strKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] strKey
    {
      get { return _strKey; }
      set { _strKey = value; }
    }
    private readonly global::System.Collections.Generic.List<byte[]> _fieldVecList = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(3, Name=@"fieldVecList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> fieldVecList
    {
      get { return _fieldVecList; }
    }
  
    private readonly global::System.Collections.Generic.List<byte[]> _valueVecList = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(4, Name=@"valueVecList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> valueVecList
    {
      get { return _valueVecList; }
    }
  
    private long _bExit;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"bExit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long bExit
    {
      get { return _bExit; }
      set { _bExit = value; }
    }
    private long _nreqid;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"nreqid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long nreqid
    {
      get { return _nreqid; }
      set { _nreqid = value; }
    }
    private long _nRet;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"nRet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long nRet
    {
      get { return _nRet; }
      set { _nRet = value; }
    }
    private long _eType;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"eType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long eType
    {
      get { return _eType; }
      set { _eType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackMysqlServerInfo")]
  public partial class PackMysqlServerInfo : global::ProtoBuf.IExtensible
  {
    public PackMysqlServerInfo() {}
    
    private long _nRconnectTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nRconnectTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long nRconnectTime
    {
      get { return _nRconnectTime; }
      set { _nRconnectTime = value; }
    }
    private long _nRconneCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nRconneCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long nRconneCount
    {
      get { return _nRconneCount; }
      set { _nRconneCount = value; }
    }
    private long _nPort;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long nPort
    {
      get { return _nPort; }
      set { _nPort = value; }
    }
    private byte[] _strDBName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"strDBName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] strDBName
    {
      get { return _strDBName; }
      set { _strDBName = value; }
    }
    private byte[] _strDnsIp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"strDnsIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] strDnsIp
    {
      get { return _strDnsIp; }
      set { _strDnsIp = value; }
    }
    private byte[] _strDBUser;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"strDBUser", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] strDBUser
    {
      get { return _strDBUser; }
      set { _strDBUser = value; }
    }
    private byte[] _strDBPwd;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"strDBPwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] strDBPwd
    {
      get { return _strDBPwd; }
      set { _strDBPwd = value; }
    }
    private long _nServerID;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"nServerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long nServerID
    {
      get { return _nServerID; }
      set { _nServerID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}